parserOptions:
  sourceType: 'module'
  ecmaVersion: 8
extends: 'eslint:recommended'
env:
  browser: true
  es6: true
ignorePatterns:
  - webpack.config.js
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
    - allow:
      - warn
      - error
