parserOptions:
  sourceType: 'module'
  ecmaVersion: 'latest'
extends: 'eslint:recommended'
env:
  browser: true
  es6: true
ignorePatterns:
  - webpack.config.js
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
    - allow:
      - warn
      - error
  no-await-in-loop:
    - error
  no-promise-executor-return:
    - error
  require-atomic-updates:
    - error
  max-nested-callbacks:
    - error
    - 3
  prefer-promise-reject-errors:
    - error
