language: php

sudo: false

addons:
  postgresql: "9.4"

services:
  - postgresql

php:
  - 7.0
  - nightly
matrix:
  allow_failures:
    - php: nightly

before_script:
  - psql -U travis -c 'create database travis_ci_test'
  - psql -U travis -d travis_ci_test -c 'create extension postgis'
  - cp .env.travis .env
  - travis_retry composer self-update --preview
  - travis_retry composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - php artisan serve &
  - sleep 5 # Give artisan some time to start serving

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text
