language: php

sudo: false
dist: trusty

cache:
  - apt

addons:
  chrome: stable
  postgresql: "9.6"
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/nginx/development/ubuntu trusty main'
    packages:
      - nginx
      - realpath
      - postgresql-9.6-postgis-2.3
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - $(ls tests/Browser/screenshots/*.png | tr "\n" ":")
      - $(ls tests/Browser/console/*.log | tr "\n" ":")
      - $(ls storage/logs/*.log | tr "\n" ":")
      - $(ls /tmp/*.log | tr "\n" ":")

services:
  - postgresql

env:
  global:
    - setup=basic

php:
  - 7.1

before_install:
  - cp .env.travis .env
  - echo 'error_log = "/tmp/php.error.log"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - psql -U travis -c 'create database travis_ci_test'
  - psql -U travis -d travis_ci_test -c 'create extension postgis'
  - travis_retry composer self-update --preview

install:
  - if [[ $setup = 'basic' ]];  then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --no-interaction --prefer-dist --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-dist --prefer-lowest --prefer-stable; fi
  - travis/install-nginx.sh

before_script:
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - php artisan token:generate
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9515 http://localhost:8000 &
  - sleep 5 # Give artisan some time to start serving

script:
  - php vendor/bin/phpunit --coverage-text
  - php artisan dusk
  - php vendor/bin/security-checker security:check ./composer.lock --end-point=http://security.sensiolabs.org/check_lock
