#!/usr/bin/env zsh

echo "compressing app.css and prism files"
zopfli --i100 ./public/assets/css/app.css
zopfli --i100 ./public/assets/prism/prism.css
zopfli --i100 ./public/assets/prism/prism.js
brotli --force --quality=11 --output=./public/assets/css/app.css.br -- ./public/assets/css/app.css
brotli --force --quality=11 --output=./public/assets/prism/prism.css.br -- ./public/assets/prism/prism.css
brotli --force --quality=11 --output=./public/assets/prism/prism.js.br -- ./public/assets/prism/prism.js

echo "compressing js assets"
for file in ./public/assets/js/*.js
do
    zopfli --i100 $file
    brotli --force --quality=11 --output=$file.br -- $file
done

echo "compressing frontend assets"
for file in ./public/assets/frontend/*.css
do
    zopfli --i100 $file
    brotli --force --quality=11 --output=$file.br -- $file
done
