#!/usr/bin/env zsh

for file in ./public/assets/js/*.js
do
    echo "uglifying `basename $file`"
    uglifyjs --verbose --compress --source-map content=${file:2}.map,url=`basename $file`.map,filename=${file:2}.map,includeSources=true --output $file $file
done
